qemu/atomic.h: prefix qemu_ to solve <stdatomic.h> collisions
clang's C11 atomic_fetch_*() functions only take a C11 atomic type
pointer argument. QEMU uses direct types (int, etc) and this causes a
compiler error when a QEMU code calls these functions in a source file
that also included <stdatomic.h> via a system header file:

  $ CC=clang CXX=clang++ ./configure ... && make
  ../util/async.c:79:17: error: address argument to atomic operation must be a pointer to _Atomic type ('unsigned int *' invalid)

Avoid using atomic_*() names in QEMU's atomic.h since that namespace is
used by <stdatomic.h>. Prefix QEMU's APIs with qemu_ so that atomic.h
and <stdatomic.h> can co-exist.

This patch was generated using:

  $ git grep -h -o '\<atomic\(64\)\?_[a-z0-9_]\+' include/qemu/atomic.h | \
    sort -u >/tmp/changed_identifiers
  $ for identifier in $(</tmp/changed_identifiers); do
       sed -i "s%\<$identifier\>%qemu_$identifier%g" \
           $(git grep -I -l "\<$identifier\>")
    done

I manually fixed line-wrap issues and misaligned rST tables.

Signed-off-by: Stefan Hajnoczi <stefanha@redhat.com>
---
v2:
 * The diff of my manual fixups is available here:
   https://vmsplice.net/~stefan/atomic-namespace-pre-fixups.diff
   - Dropping #ifndef qemu_atomic_fetch_add in atomic.h
   - atomic_##X(haddr, val) glue macros not caught by grep
   - Keep atomic_add-bench name
   - C preprocessor backslash-newline ('\') column alignment
   - Line wrapping
 * Use grep -I to avoid accidentally modifying binary files (RISC-V
   OpenSBI ELFs) [Eric Blake]
 * Tweak .gitorder to show atomic.h changes first [Eric Blake]
 * Update grep commands in commit description so reviewers can reproduce
   mechanical changes [Eric Blake]